public class CuentasInicializar {
    public CuentasInicializar(){

    }

    public static void PrimerMetodo() {
        
    }

    public static integer SegundoMetodo(){
        Integer a =0;
        for (Integer i=0;i<100;i++) {
            Integer res= a+(a+1);
        }
        Return res;
    }

    public static List<Account> InsertAccounts(){
        List<Account> res = new List<Account>();
        return res;
    }
}